/*
File: scratch-config.hpp
Description: Contains all defines for global constants in CScratch
*/

#pragma once

#define CORE_ENGINE_JOB_COUNT 2

#define TARGET_FRAMERATE 60
#define SCRATCHK_MAX_KEYCODE 337 // KEY_KP_EQUAL + 1

#define STAGE_MIN_X (-240)
#define STAGE_MAX_X 240
#define STAGE_MIN_Y (-180)
#define STAGE_MAX_Y 180
#define STAGE_SIZE_X (STAGE_MAX_X - STAGE_MIN_X)
#define STAGE_SIZE_Y (STAGE_MAX_Y - STAGE_MIN_Y)
#define STAGE_MIN_X_FLOAT (-240.0)
#define STAGE_MAX_X_FLOAT 240.0
#define STAGE_MIN_Y_FLOAT (-180.0)
#define STAGE_MAX_Y_FLOAT 180.0
#define STAGE_SIZE_X_FLOAT (STAGE_MAX_X_FLOAT - STAGE_MIN_X_FLOAT)
#define STAGE_SIZE_Y_FLOAT (STAGE_MAX_Y_FLOAT - STAGE_MIN_Y_FLOAT)
#define SPRITE_STICKOUT_MINIMUM 16.0
#define SPRITE_SIZE_DIMENSION_MINIMUM 5.0
#define SPRITE_ROTATION_MIN (-180)
#define SPRITE_ROTATION_MAX 180
#define SPRITE_ROTATION_RANGE (SPRITE_ROTATION_MAX - SPRITE_ROTATION_MIN)
#define SPRITE_ROTATION_MIN_FLOAT (-180.0)
#define SPRITE_ROTATION_MAX_FLOAT 180.0
#define SPRITE_ROTATION_RANGE_FLOAT (SPRITE_ROTATION_MAX_FLOAT - SPRITE_ROTATION_MIN_FLOAT)
#define SPRITE_DEFAULT_SIZE 100.0
#define SPRITE_MAX_SIZE_X_FLOAT 720.0
#define SPRITE_MAX_SIZE_Y_FLOAT 540.0

#define COLOR_BLACK {0, 0, 0, 255}
#define COLOR_WHITE {255, 255, 255, 255}